services:
  # Backend API Service
  - type: web
    name: golf-league-api
    env: node
    buildCommand: npm ci
    startCommand: npm run server
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: NODE_ENV
        value: production

  # Frontend Static Site
  - type: web
    name: golf-league-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: golf-league-api
          envVarKey: RENDER_EXTERNAL_URL
